In [11]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [12]:
sales = pd.read_csv("D:/Data Analysis/Tamweely Train/Brazilian E-Commerce Dataset/data/sales_master.csv")

sales.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,1,credit_card,2,146.87,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,1,credit_card,8,335.48,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,1,credit_card,7,157.73,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,1,credit_card,1,173.30,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,1,credit_card,8,252.25,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0

In [13]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    117601 non-null  str
 1   customer_unique_id             117601 non-null  str
 2   customer_zip_code_prefix       117601 non-null  int64
 3   customer_city                  117601 non-null  str
 4   customer_state                 117601 non-null  str
 5   order_id                       117601 non-null  str
 6   order_status                   117601 non-null  str
 7   order_purchase_timestamp       117601 non-null  str
 8   order_approved_at              117586 non-null  str
 9   order_delivered_carrier_date   116356 non-null  str
 10  order_delivered_customer_date  115034 non-null  str
 11  order_estimated_delivery_date  117601 non-null  str
 12  order_item_id                  117601 non-null  int64
 13  product_id                     117601 non-null  str
 14  seller_id                      117601 non-null  str
 15  shipping_limit_date            117601 non-null  str
 16  price                          117601 non-null  float64
 17  freight_value                  117601 non-null  float64
 18  payment_sequential             117601 non-null  int64
 19  payment_type                   117601 non-null  str
 20  payment_installments           117601 non-null  int64
 21  payment_value                  117601 non-null  float64
 22  product_category_name          115903 non-null  str
 23  product_name_lenght            115903 non-null  float64
 24  product_description_lenght     115903 non-null  float64
 25  product_photos_qty             115903 non-null  float64
 26  product_weight_g               117581 non-null  float64
 27  product_length_cm              117581 non-null  float64
 28  product_height_cm              117581 non-null  float64
 29  product_width_cm               117581 non-null  float64
dtypes: float64(10), int64(4), str(16)
memory usage: 26.9 MB

In [14]:
sales.isnull().sum()

customer_id                         0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_id                            0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1245
order_delivered_customer_date    2567
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
product_category_name            1698
product_name_lenght              1698
product_description_lenght       1698
product_photos_qty               1698
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
dtype: int64

In [15]:
print("Duplicates Before :", sales.duplicated().sum())

sales = sales.drop_duplicates()

print("Duplicates After :", sales.duplicated().sum())

Duplicates Before : 0
Duplicates After : 0

In [16]:
sales["payment_value"] = sales["payment_value"].fillna(
    sales["payment_value"].median()
)

In [17]:
sales["order_purchase_timestamp"] = pd.to_datetime(
    sales["order_purchase_timestamp"]
)

sales["order_delivered_customer_date"] = pd.to_datetime(
    sales["order_delivered_customer_date"]
)
sales["order_delivered_carrier_date"] = pd.to_datetime(
    sales["order_delivered_carrier_date"]
)
sales["order_estimated_delivery_date"] = pd.to_datetime(
    sales["order_estimated_delivery_date"]
)
sales["shipping_limit_date"] = pd.to_datetime(
    sales["shipping_limit_date"]
)

In [18]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    117601 non-null  str
 1   customer_unique_id             117601 non-null  str
 2   customer_zip_code_prefix       117601 non-null  int64
 3   customer_city                  117601 non-null  str
 4   customer_state                 117601 non-null  str
 5   order_id                       117601 non-null  str
 6   order_status                   117601 non-null  str
 7   order_purchase_timestamp       117601 non-null  datetime64[us]
 8   order_approved_at              117586 non-null  str
 9   order_delivered_carrier_date   116356 non-null  datetime64[us]
 10  order_delivered_customer_date  115034 non-null  datetime64[us]
 11  order_estimated_delivery_date  117601 non-null  datetime64[us]
 12  order_item_id                  117601 non-null  int64
 13  product_id                     117601 non-null  str
 14  seller_id                      117601 non-null  str
 15  shipping_limit_date            117601 non-null  datetime64[us]
 16  price                          117601 non-null  float64
 17  freight_value                  117601 non-null  float64
 18  payment_sequential             117601 non-null  int64
 19  payment_type                   117601 non-null  str
 20  payment_installments           117601 non-null  int64
 21  payment_value                  117601 non-null  float64
 22  product_category_name          115903 non-null  str
 23  product_name_lenght            115903 non-null  float64
 24  product_description_lenght     115903 non-null  float64
 25  product_photos_qty             115903 non-null  float64
 26  product_weight_g               117581 non-null  float64
 27  product_length_cm              117581 non-null  float64
 28  product_height_cm              117581 non-null  float64
 29  product_width_cm               117581 non-null  float64
dtypes: datetime64[us](5), float64(10), int64(4), str(11)
memory usage: 26.9 MB

In [19]:
sales["Delivery_Days"] = (
    sales["order_delivered_customer_date"]
    - sales["order_purchase_timestamp"]
).dt.days

In [20]:
sales["Order_Month"] = sales["order_purchase_timestamp"].dt.month

In [21]:
sales["Order_Year"] = sales["order_purchase_timestamp"].dt.year

In [22]:
sales = sales.rename(columns={

    "customer_city":"City",

    "customer_state":"State",

    "payment_value":"Payment",

    "price":"Revenue"

})

In [23]:
sales["Order_Year"] = sales["Order_Year"].astype("int")

sales["Order_Month"] = sales["Order_Month"].astype("int")

sales["Delivery_Days"] = sales["Delivery_Days"].astype("float")

In [24]:
sales["product_category_name"] = (

    sales["product_category_name"]

    .str.lower()

    .str.strip()

)

In [25]:
Q1 = sales["Payment"].quantile(.25)

Q3 = sales["Payment"].quantile(.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR

upper = Q3+1.5*IQR

outliers = sales[
    (sales["Payment"]<lower) |
    (sales["Payment"]>upper)
]

print(outliers.shape)

(9495, 33)

In [26]:
sales = sales[
    (sales["Payment"]>0) &
    (sales["Revenue"]>0)
]

In [27]:
sales[["order_id", "order_item_id"]].head(20)

                            order_id  order_item_id
0   00e7ee1b050b8499577073aeb2a297a1              1
1   29150127e6685892b6eab3eec79f59c7              1
2   b2059ed67ce144a36e2aa97d2c9e9ad2              1
3   951670f92359f4fe4a63112aa7306eba              1
4   6b7d50bd145f6fc7f33cebabd7e49d0f              1
5   5741ea1f91b5fbab2bd2dc653a5b5099              1
6   36e694cf4cbc2a4803200c35e84abdc4              1
7   1093c8304c7a003280dd34598194913d              1
8   1ebeea841c590e86a14a0d7a48e7d062              1
9   7433cbcc783205509d66a5260da5b574              1
10  8428e578bb1cf839ae26a6b7615502b9              1
11  f86c5ed7048ac10eb88ec21c00f71892              1
12  83d8f70418eefd96f37b483dff430305              1
13  852d2f4d37773bcbc21c8e09a05a4ea5              1
14  6c949e670b5d33dc8fb8ad25b6da4860              1
15  eac76692452422620996fe5e1a7f8bb0              1
16  72bab69c50432c6f94d8b50a5f84b69a              1
17  ec28553b12bef4b538e5d7454464a1c6              1
18  17825f24877a9289214c301ae0c9424b              1
19  17825f24877a9289214c301ae0c9424b              1

In [28]:
sales["order_item_id"].value_counts().sort_index()

order_item_id
1     103050
2      10238
3       2375
4        986
5        469
6        262
7         60
8         36
9         28
10        25
11        17
12        13
13         8
14         7
15         5
16         3
17         3
18         3
19         3
20         3
21         1
Name: count, dtype: int64

In [29]:
sales["quantity"] = (
    sales.groupby("order_id")["order_item_id"]
         .transform("max")
)

In [30]:
sales[["order_id", "order_item_id", "quantity"]].head(20)

                            order_id  order_item_id  quantity
0   00e7ee1b050b8499577073aeb2a297a1              1         1
1   29150127e6685892b6eab3eec79f59c7              1         1
2   b2059ed67ce144a36e2aa97d2c9e9ad2              1         1
3   951670f92359f4fe4a63112aa7306eba              1         1
4   6b7d50bd145f6fc7f33cebabd7e49d0f              1         1
5   5741ea1f91b5fbab2bd2dc653a5b5099              1         1
6   36e694cf4cbc2a4803200c35e84abdc4              1         1
7   1093c8304c7a003280dd34598194913d              1         1
8   1ebeea841c590e86a14a0d7a48e7d062              1         1
9   7433cbcc783205509d66a5260da5b574              1         1
10  8428e578bb1cf839ae26a6b7615502b9              1         1
11  f86c5ed7048ac10eb88ec21c00f71892              1         1
12  83d8f70418eefd96f37b483dff430305              1         1
13  852d2f4d37773bcbc21c8e09a05a4ea5              1         1
14  6c949e670b5d33dc8fb8ad25b6da4860              1         1
15  eac76692452422620996fe5e1a7f8bb0              1         1
16  72bab69c50432c6f94d8b50a5f84b69a              1         1
17  ec28553b12bef4b538e5d7454464a1c6              1         1
18  17825f24877a9289214c301ae0c9424b              1         1
19  17825f24877a9289214c301ae0c9424b              1         1

In [31]:
sales[sales["order_item_id"] > 1][["order_id", "order_item_id"]].head(20)

                             order_id  order_item_id
23   aaff8afa47c8426e414a6d908a97713c              2
24   aaff8afa47c8426e414a6d908a97713c              3
37   77b062be7c5bd21712905feb8e1cfeed              2
51   14282bc70be9bdda515182fb1ce62af4              2
64   07429f7601b56a66d1854c79a2f5c9e5              2
66   f481e2c2c039ab1665d048d7e2cf5e00              2
67   f481e2c2c039ab1665d048d7e2cf5e00              3
68   f481e2c2c039ab1665d048d7e2cf5e00              4
69   f481e2c2c039ab1665d048d7e2cf5e00              5
86   bce1e6fae8db0875cde2048ee4220438              2
90   0c65b54ed2c147ffd0092eb2308ee63d              2
106  23c0fb66f3afa483b302cc740b14f17b              2
126  d152d9b39cef5941978b389e5ffee780              2
142  fc24b77521e400e8290a902026efcc85              2
175  a70e2a7c5779986b66893322855c4932              2
187  db7374d1f9c8965e0fbbc1fd1cc916fe              2
194  0bb96548fdaf9fb98f6a72c4936a54d1              2
195  0bb96548fdaf9fb98f6a72c4936a54d1              3
211  4c7061e57405537a32f8c9dd0a194d68              2
212  4c7061e57405537a32f8c9dd0a194d68              3

In [32]:
sales.groupby("order_id")["order_item_id"].max().sort_values(ascending=False).head(20)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
637617b3ffe9e2f7a2411243829226d0    12
c05d6a79e55da72ca780ce90364abed9    12
af822dacd6f5cff7376413c03a388bb7    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
2c2a19b5703863c908512d135aa6accc    12
5a3b1c29a49756e75f1ef513383c0c12    11
71dab1155600756af6de79de92e712e3    11
6c355e2913545fa6f72c40cbca57729e    11
7f2c22c54cbae55091a09a9653fd2b8a    11
a483ffe0ce133740ab12ebcba8a3ccf9    10
9aec4e1ae90b23c7bf2d2b3bfafbd943    10
30bdf3d824d824610a49887486debcaf    10
Name: order_item_id, dtype: int64

In [33]:
sales["quantity"] = (
    sales.groupby("order_id")["order_item_id"]
    .transform("max")
)

In [34]:
sales.loc[
    sales["order_id"] == "8272b63d03f5f79c56e9e4120aec44ef",
    ["order_id", "order_item_id", "quantity"]
]

                               order_id  order_item_id  quantity
55751  8272b63d03f5f79c56e9e4120aec44ef              1        21
55752  8272b63d03f5f79c56e9e4120aec44ef              2        21
55753  8272b63d03f5f79c56e9e4120aec44ef              3        21
55754  8272b63d03f5f79c56e9e4120aec44ef              4        21
55755  8272b63d03f5f79c56e9e4120aec44ef              5        21
55756  8272b63d03f5f79c56e9e4120aec44ef              6        21
55757  8272b63d03f5f79c56e9e4120aec44ef              7        21
55758  8272b63d03f5f79c56e9e4120aec44ef              8        21
55759  8272b63d03f5f79c56e9e4120aec44ef              9        21
55760  8272b63d03f5f79c56e9e4120aec44ef             10        21
55761  8272b63d03f5f79c56e9e4120aec44ef             11        21
55762  8272b63d03f5f79c56e9e4120aec44ef             12        21
55763  8272b63d03f5f79c56e9e4120aec44ef             13        21
55764  8272b63d03f5f79c56e9e4120aec44ef             14        21
55765  8272b63d03f5f79c56e9e4120aec44ef             15        21
55766  8272b63d03f5f79c56e9e4120aec44ef             16        21
55767  8272b63d03f5f79c56e9e4120aec44ef             17        21
55768  8272b63d03f5f79c56e9e4120aec44ef             18        21
55769  8272b63d03f5f79c56e9e4120aec44ef             19        21
55770  8272b63d03f5f79c56e9e4120aec44ef             20        21
55771  8272b63d03f5f79c56e9e4120aec44ef             21        21

In [35]:
sales["Total_Revenue"] = sales["Payment"] * sales["quantity"]

In [36]:
sales["Profit"] = sales["Total_Revenue"] * 0.20

In [37]:
sales["Delivery_Status"] = np.where(

    sales["Delivery_Days"]<=7,

    "Fast",

    "Delayed"

)

In [38]:
sales["Customer_Type"] = np.where(

    sales.duplicated("customer_id"),

    "Returning",

    "New"

)

In [39]:
report = {

"Missing Values":sales.isnull().sum(),

"Duplicate Count":sales.duplicated().sum(),

"Outliers":len(outliers),

"Data Types":sales.dtypes,

"Cleaned Records":len(sales)

}

report

{'Missing Values': customer_id                         0
 customer_unique_id                  0
 customer_zip_code_prefix            0
 City                                0
 State                               0
 order_id                            0
 order_status                        0
 order_purchase_timestamp            0
 order_approved_at                  15
 order_delivered_carrier_date     1245
 order_delivered_customer_date    2565
 order_estimated_delivery_date       0
 order_item_id                       0
 product_id                          0
 seller_id                           0
 shipping_limit_date                 0
 Revenue                             0
 freight_value                       0
 payment_sequential                  0
 payment_type                        0
 payment_installments                0
 Payment                             0
 product_category_name            1698
 product_name_lenght              1698
 product_description_lenght       1698
 product_photos_qty               1698
 product_weight_g                   20
 product_length_cm                  20
 product_height_cm                  20
 product_width_cm                   20
 Delivery_Days                    2565
 Order_Month                         0
 Order_Year                          0
 quantity                            0
 Total_Revenue                       0
 Profit                              0
 Delivery_Status                     0
 Customer_Type                       0
 dtype: int64,
 'Duplicate Count': np.int64(0),
 'Outliers': 9495,
 'Data Types': customer_id                                 str
 customer_unique_id                          str
 customer_zip_code_prefix                  int64
 City                                        str
 State                                       str
 order_id                                    str
 order_status                                str
 order_purchase_timestamp         datetime64[us]
 order_approved_at                           str
 order_delivered_carrier_date     datetime64[us]
 order_delivered_customer_date    datetime64[us]
 order_estimated_delivery_date    datetime64[us]
 order_item_id                             int64
 product_id                                  str
 seller_id                                   str
 shipping_limit_date              datetime64[us]
 Revenue                                 float64
 freight_value                           float64
 payment_sequential                        int64
 payment_type                                str
 payment_installments                      int64
 Payment                                 float64
 product_category_name                       str
 product_name_lenght                     float64
 product_description_lenght              float64
 product_photos_qty                      float64
 product_weight_g                        float64
 product_length_cm                       float64
 product_height_cm                       float64
 product_width_cm                        float64
 Delivery_Days                           float64
 Order_Month                               int64
 Order_Year                                int64
 quantity                                  int64
 Total_Revenue                           float64
 Profit                                  float64
 Delivery_Status                             str
 Customer_Type                               str
 dtype: object,
 'Cleaned Records': 117595}

In [41]:
sales.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,City,State,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,Revenue,freight_value,payment_sequential,payment_type,payment_installments,Payment,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,Delivery_Days,Order_Month,Order_Year,quantity,Total_Revenue,Profit,Delivery_Status,Customer_Type
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,1,credit_card,2,146.87,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0,8.0,5,2017,1,146.87,29.374,Delayed,New
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,1,credit_card,8,335.48,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0,16.0,1,2018,1,335.48,67.096,Delayed,New
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,1,credit_card,7,157.73,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0,26.0,5,2018,1,157.73,31.546,Delayed,New
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,1,credit_card,1,173.30,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0,14.0,3,2018,1,173.30,34.660,Delayed,New
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,1,credit_card,8,252.25,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0,11.0,7,2018,1,252.25,50.450,Delayed,New

In [42]:
sales["Delivery_Days"] = sales["Delivery_Days"].fillna(
    sales["Delivery_Days"].median()
)

In [43]:
sales["product_category_name"] = sales["product_category_name"].fillna("Unknown")

In [44]:
sales["product_weight_g"] = sales["product_weight_g"].fillna(
    sales["product_weight_g"].median()
)

In [45]:
sales["product_length_cm"] = sales["product_length_cm"].fillna(
    sales["product_length_cm"].median()
)

In [46]:
sales["product_height_cm"] = sales["product_height_cm"].fillna(
    sales["product_height_cm"].median()
)

In [47]:
sales["product_width_cm"] = sales["product_width_cm"].fillna(
    sales["product_width_cm"].median()
)

In [48]:
sales.drop(columns=["product_name_lenght"], inplace=True)

In [49]:
sales.drop(columns=["product_description_lenght"], inplace=True)

In [50]:
sales.drop(columns=["product_photos_qty"], inplace=True)

In [52]:
sales.drop(
    columns=[
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ],
    inplace=True
)

In [53]:
sales.info()

<class 'pandas.DataFrame'>
Index: 117595 entries, 0 to 117600
Data columns (total 32 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    117595 non-null  str
 1   customer_unique_id             117595 non-null  str
 2   customer_zip_code_prefix       117595 non-null  int64
 3   City                           117595 non-null  str
 4   State                          117595 non-null  str
 5   order_id                       117595 non-null  str
 6   order_status                   117595 non-null  str
 7   order_purchase_timestamp       117595 non-null  datetime64[us]
 8   order_estimated_delivery_date  117595 non-null  datetime64[us]
 9   order_item_id                  117595 non-null  int64
 10  product_id                     117595 non-null  str
 11  seller_id                      117595 non-null  str
 12  shipping_limit_date            117595 non-null  datetime64[us]
 13  Revenue                        117595 non-null  float64
 14  freight_value                  117595 non-null  float64
 15  payment_sequential             117595 non-null  int64
 16  payment_type                   117595 non-null  str
 17  payment_installments           117595 non-null  int64
 18  Payment                        117595 non-null  float64
 19  product_category_name          117595 non-null  str
 20  product_weight_g               117595 non-null  float64
 21  product_length_cm              117595 non-null  float64
 22  product_height_cm              117595 non-null  float64
 23  product_width_cm               117595 non-null  float64
 24  Delivery_Days                  117595 non-null  float64
 25  Order_Month                    117595 non-null  int64
 26  Order_Year                     117595 non-null  int64
 27  quantity                       117595 non-null  int64
 28  Total_Revenue                  117595 non-null  float64
 29  Profit                         117595 non-null  float64
 30  Delivery_Status                117595 non-null  str
 31  Customer_Type                  117595 non-null  str
dtypes: datetime64[us](3), float64(10), int64(7), str(12)
memory usage: 29.6 MB

In [54]:
sales.isnull().sum()

customer_id                      0
customer_unique_id               0
customer_zip_code_prefix         0
City                             0
State                            0
order_id                         0
order_status                     0
order_purchase_timestamp         0
order_estimated_delivery_date    0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
Revenue                          0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
Payment                          0
product_category_name            0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
Delivery_Days                    0
Order_Month                      0
Order_Year                       0
quantity                         0
Total_Revenue                    0
Profit                           0
Delivery_Status                  0
Customer_Type                    0
dtype: int64

In [55]:
sales.to_csv("Sales_Master_Clean.csv", index=False)

In [56]:
import os

print(os.getcwd())

d:\Data Analysis\Tamweely Train\Brazilian E-Commerce Dataset\python

In [57]:
sales.to_excel("D:\\Data Analysis\\Tamweely Train\\Brazilian E-Commerce Dataset\\powerbi\\data\\Sales_Master_Clean.xlsx", index=False)